command = /opt/homebrew/bin/fish --login --interactive
theme = catppuccin-mocha
font-size = 18
font-feature = -calt
window-width = 120
window-height = 1000
window-padding-balance = true
window-padding-x = 0
window-padding-y = 0
confirm-close-surface = false
macos-option-as-alt = true
copy-on-select = clipboard
background-opacity = 0.7
alpha-blending = linear-corrected

keybind = super+s=text:\x01S

# map specific navigation keys manually because they have other mappings in ghostty
# before others so the subsequent mappings show on the tab bar
keybind = super+plus=goto_tab:1
keybind = super+left_bracket=goto_tab:2

keybind = ctrl+shift+alt+h=goto_tab:1
keybind = ctrl+shift+alt+t=goto_tab:2
keybind = ctrl+shift+alt+n=goto_tab:3
keybind = ctrl+shift+alt+s=goto_tab:4
keybind = ctrl+shift+alt+x=close_surface

# Ghostty sends alt-f/b for alt-left/right
keybind = alt+left=unbind
keybind = alt+right=unbind