command = /opt/homebrew/bin/fish --login --interactive
theme = catppuccin-mocha
font-size = 18
font-feature = -calt
window-width = 120
window-height = 1000
confirm-close-surface = false
macos-option-as-alt = true
copy-on-select = clipboard

keybind = ctrl+shift+alt+f=next_tab
keybind = ctrl+shift+alt+b=previous_tab
keybind = ctrl+shift+alt+w=close_surface
# map specific navigation keys manually because they have other mappings in ghostty
keybind = super+plus=goto_tab:1
keybind = super+left_bracket=goto_tab:2
