# don't index floaX
blacklist = ["scratch"]

[default_session]
startup_command = "nvim -c ':lua Snacks.dashboard.pick(\\'oldfiles\\', { filter = { cwd = true } })'"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "neovim config "
path = "~/.config/nvim"
startup_command = "nvim"

