
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/markjarjour/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/markjarjour/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/markjarjour/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/markjarjour/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# fnm env
eval "$(fnm env --use-on-cd --shell zsh)"

alias pn=pnpm

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

parse_git_branch() {
    git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/[\1] /p'
}
COLOR_DEF='%f'
COLOR_DIR='%F{197}'
COLOR_GIT='%F{39}'
NEWLINE=$'\n'
setopt PROMPT_SUBST
export PROMPT='${COLOR_DIR}%d ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF}%% '

# Created by `pipx` on 2024-07-16 02:25:51
export PATH="$PATH:/Users/markjarjour/.local/bin"

export PATH=$PATH:$(go env GOPATH)/bin