# don't index floaX
blacklist = ["scratch"]

[default_session]
startup_command = "nvim -c ':lua Snacks.picker.smart()'"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "neovim config "
path = "~/.config/nvim"
startup_command = "nvim"

